### ISSUE TITLE
Segmentation fault with array of variadic functions

### ISSUE THREAD

**Issue by AndreaOrru** [zig-lang/zig#377]
```
var foos = []fn(...) { foo1, foo2 };

fn foo1(args: ...) {}
fn foo2(args: ...) {}

pub fn main() -> %void {
    foos[0]();
}
```

Stack trace:
```
(gdb) backtrace
#0  0x00005555559ade9a in ir_gen_node_raw (irb=0x7fffffffda90, node=0x0, scope=0x555556cde4c0, lval=...) at /home/andrea/zig/src/ir.cpp:5866
#1  0x00005555559ae63e in ir_gen_node_extra (irb=0x7fffffffda90, node=0x0, scope=0x555556cde4c0, lval=...) at /home/andrea/zig/src/ir.cpp:5965
#2  0x00005555559ae6ce in ir_gen_node (irb=0x7fffffffda90, node=0x0, scope=0x555556cde4c0) at /home/andrea/zig/src/ir.cpp:5971
#3  0x00005555559adda5 in ir_gen_fn_proto (irb=0x7fffffffda90, parent_scope=0x555556cde4c0, node=0x555556cdbc70) at /home/andrea/zig/src/ir.cpp:5849
#4  0x00005555559ae5aa in ir_gen_node_raw (irb=0x7fffffffda90, node=0x555556cdbc70, scope=0x555556cde4c0, lval=...) at /home/andrea/zig/src/ir.cpp:5951
#5  0x00005555559ae63e in ir_gen_node_extra (irb=0x7fffffffda90, node=0x555556cdbc70, scope=0x555556cde4c0, lval=...) at /home/andrea/zig/src/ir.cpp:5965
#6  0x00005555559ae6ce in ir_gen_node (irb=0x7fffffffda90, node=0x555556cdbc70, scope=0x555556cde4c0) at /home/andrea/zig/src/ir.cpp:5971
#7  0x00005555559aacde in ir_gen_array_type (irb=0x7fffffffda90, scope=0x555556cde4c0, node=0x555556cdbbd0) at /home/andrea/zig/src/ir.cpp:5116
#8  0x00005555559ae1fa in ir_gen_node_raw (irb=0x7fffffffda90, node=0x555556cdbbd0, scope=0x555556cde4c0, lval=...) at /home/andrea/zig/src/ir.cpp:5913
#9  0x00005555559ae63e in ir_gen_node_extra (irb=0x7fffffffda90, node=0x555556cdbbd0, scope=0x555556cde4c0, lval=...) at /home/andrea/zig/src/ir.cpp:5965
#10 0x00005555559ae6ce in ir_gen_node (irb=0x7fffffffda90, node=0x555556cdbbd0, scope=0x555556cde4c0) at /home/andrea/zig/src/ir.cpp:5971
#11 0x00005555559a85fe in ir_gen_container_init_expr (irb=0x7fffffffda90, scope=0x555556cde4c0, node=0x555556cdbe50) at /home/andrea/zig/src/ir.cpp:4598
#12 0x00005555559ae071 in ir_gen_node_raw (irb=0x7fffffffda90, node=0x555556cdbe50, scope=0x555556cde4c0, lval=...) at /home/andrea/zig/src/ir.cpp:5895
#13 0x00005555559ae63e in ir_gen_node_extra (irb=0x7fffffffda90, node=0x555556cdbe50, scope=0x555556cde4c0, lval=...) at /home/andrea/zig/src/ir.cpp:5965
#14 0x00005555559aead4 in ir_gen (codegen=0x555556c9fda0, node=0x555556cdbe50, scope=0x555556cde4c0, ir_executable=0x7fffffffdbb0)
    at /home/andrea/zig/src/ir.cpp:6051
#15 0x00005555559b0de0 in ir_eval_const_value (codegen=0x555556c9fda0, scope=0x555556cde4c0, node=0x555556cdbe50, expected_type=0x0,
    backward_branch_count=0x7fffffffdcd8, backward_branch_quota=1000, fn_entry=0x0, c_import_buf=0x0, source_node=0x555556cdbe50, exec_name=0x555556cdc320,
    parent_exec=0x0) at /home/andrea/zig/src/ir.cpp:6826
#16 0x000055555596f811 in analyze_const_value (g=0x555556c9fda0, scope=0x555556cde4c0, node=0x555556cdbe50, type_entry=0x0, type_name=0x555556cdc320)
    at /home/andrea/zig/src/analyze.cpp:978
#17 0x0000555555973d42 in resolve_decl_var (g=0x555556c9fda0, tld_var=0x555556d08360) at /home/andrea/zig/src/analyze.cpp:2364
#18 0x00005555559740ad in resolve_top_level_decl (g=0x555556c9fda0, tld=0x555556d08360, pointer_only=true) at /home/andrea/zig/src/analyze.cpp:2418
#19 0x00005555559c7288 in ir_analyze_instruction_decl_ref (ira=0x7fffffffdea0, instruction=0x5555573a25f0) at /home/andrea/zig/src/ir.cpp:13350
#20 0x00005555559c7bd2 in ir_analyze_instruction_nocast (ira=0x7fffffffdea0, instruction=0x5555573a25f0) at /home/andrea/zig/src/ir.cpp:13558
#21 0x00005555559c7ca8 in ir_analyze_instruction (ira=0x7fffffffdea0, instruction=0x5555573a25f0) at /home/andrea/zig/src/ir.cpp:13583
#22 0x00005555559c7f2e in ir_analyze (codegen=0x555556c9fda0, old_exec=0x5555570dd620, new_exec=0x5555570dd6c8, expected_type=0x555556e4bf60,
    expected_type_source_node=0x555556cdde50) at /home/andrea/zig/src/ir.cpp:13633
#23 0x0000555555974df3 in analyze_fn_ir (g=0x555556c9fda0, fn_table_entry=0x5555570dd5b0, return_type_node=0x555556cdde50)
    at /home/andrea/zig/src/analyze.cpp:2800
#24 0x0000555555975144 in analyze_fn_body (g=0x555556c9fda0, fn_table_entry=0x5555570dd5b0) at /home/andrea/zig/src/analyze.cpp:2858
#25 0x0000555555975d02 in semantic_analyze (g=0x555556c9fda0) at /home/andrea/zig/src/analyze.cpp:3052
#26 0x0000555555996f99 in gen_root_source (g=0x555556c9fda0) at /home/andrea/zig/src/codegen.cpp:4902
#27 0x0000555555997f51 in codegen_build (g=0x555556c9fda0) at /home/andrea/zig/src/codegen.cpp:5189
#28 0x00005555559db77f in main (argc=3, argv=0x7fffffffe598) at /home/andrea/zig/src/main.cpp:653
```

**Comment by andrewrk** [comment]
Now it properly gives this error:

```
test.zig:7:9: error: calling a generic function requires compile-time known function value
    foos[0]();
        ^
```

But you can make it compile successfully like this:

```diff
-var foos = []fn(...) { foo1, foo2 };
+const foos = []fn(...) { foo1, foo2 };
```

**Comment by AndreaOrru** [comment]
OK. Just toying with that a little bit:
```
const foos = []fn(var) { foo1, foo2 };

fn foo1(args: ...) {}
fn foo2(args: ...) {}

pub fn main() -> %void {
    foos[0]();
}
```
Segmentation fault.

**Comment by andrewrk** [comment]
I tested exactly the above case. Did you pull master and rebuild with the latest commit?

**Comment by andrewrk** [comment]
Nah we can track it here.
