### ISSUE TITLE
Unable to access slice element

### ISSUE THREAD

**Issue by AndreaOrru** [zig-lang/zig#381]
```
const vram = @intToPtr(&u8, 0x20000000)[0..0x8000];

pub fn main() -> %void {
    vram[0] = 'X';
}
```

I get an `unreachable` error when compiling.

Backtrace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff3fec3fa in __GI_abort () at abort.c:89
#2  0x00005555559eb37d in zig_panic (format=0x5555566910c0 "unreachable") at /home/andrea/zig/src/util.cpp:20
#3  0x000055555599b0c2 in zig_unreachable () at /home/andrea/zig/src/util.hpp:28
#4  0x00005555559bbb4c in ir_analyze_instruction_elem_ptr (ira=0x7fffffffde70, elem_ptr_instruction=0x5555573e2710) at /home/andrea/zig/src/ir.cpp:9997
#5  0x00005555559c79e3 in ir_analyze_instruction_nocast (ira=0x7fffffffde70, instruction=0x5555573e2710) at /home/andrea/zig/src/ir.cpp:13525
#6  0x00005555559c80e9 in ir_analyze_instruction (ira=0x7fffffffde70, instruction=0x5555573e2710) at /home/andrea/zig/src/ir.cpp:13682
#7  0x00005555559c836f in ir_analyze (codegen=0x555556ca0da0, old_exec=0x555557102730, new_exec=0x5555571027d8, expected_type=0x555556e54400,
    expected_type_source_node=0x555556cdd100) at /home/andrea/zig/src/ir.cpp:13732
#8  0x0000555555974f6d in analyze_fn_ir (g=0x555556ca0da0, fn_table_entry=0x5555571026c0, return_type_node=0x555556cdd100)
    at /home/andrea/zig/src/analyze.cpp:2812
#9  0x00005555559752be in analyze_fn_body (g=0x555556ca0da0, fn_table_entry=0x5555571026c0) at /home/andrea/zig/src/analyze.cpp:2870
#10 0x0000555555975e7c in semantic_analyze (g=0x555556ca0da0) at /home/andrea/zig/src/analyze.cpp:3064
#11 0x000055555599727a in gen_root_source (g=0x555556ca0da0) at /home/andrea/zig/src/codegen.cpp:4917
#12 0x0000555555998232 in codegen_build (g=0x555556ca0da0) at /home/andrea/zig/src/codegen.cpp:5204
#13 0x00005555559dc25b in main (argc=3, argv=0x7fffffffe568) at /home/andrea/zig/src/main.cpp:653
```

**Comment by andrewrk** [comment]
Note that you probably want:

```zig
const vram = @intToPtr(&volatile u8, 0x20000000)[0..0x8000];
```
