### ISSUE TITLE
llvm assertion error: getTypeSizeInBits on unsized

### ISSUE THREAD

**Issue by tiehuis** [zig-lang/zig#468]
Using the following snippet

```
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const HeaderWeight = enum {
    H1, H2, H3, H4, H5, H6,
};

const MdText = ArrayList(u8);

const MdNode = enum {
    Header: struct {
        text: MdText,
        weight: HeaderValue,
    },
};

test "example" {
    const a = MdNode.Header {
        .text = MdText.init(&std.debug.global_allocator),
        .weight = HeaderWeight.H1,
    };
}
```

```
zig: /home/me/get/llvm-5.0.0.src/include/llvm/IR/DataLayout.h:533: uint64_t llvm::DataLayout::getTypeSizeInBits(llvm::Type*) const: Assertion `Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"' failed.
```

Here is a backtrace:
```
#0  0x00007ffff647e8a0 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff647ff09 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff64770dc in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff6477153 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00005555582dfa4e in LLVMStoreSizeOfType ()
#5  0x0000555555fabb92 in resolve_enum_type(CodeGen*, TypeTableEntry*) [clone .part.50] ()
#6  0x0000555555fe1cd1 in ir_analyze_instruction_field_ptr(IrAnalyze*, IrInstructionFieldPtr*) ()
#7  0x0000555555ff158d in ir_analyze_instruction_nocast(IrAnalyze*, IrInstruction*) ()
#8  0x0000555555ff3912 in ir_analyze(CodeGen*, IrExecutable*, IrExecutable*, TypeTableEntry*, AstNode*) ()
#9  0x0000555555fb1612 in semantic_analyze(CodeGen*) ()
#10 0x0000555555fd1386 in codegen_build(CodeGen*) ()
#11 0x0000555555f377c3 in main ()
```

Note that the weight type `HeaderValue` is not declared anywhere.

**Comment by andrewrk** [comment]
sorry that took so long. simple fix.
