### ISSUE TITLE
getAlignmentInfo segfault on union(enum)

### ISSUE THREAD

**Issue by tiehuis** [zig-lang/zig#713]
Latest Zig master, using LLVM-5.0.1.

```
const PartialInst = union(enum) {
    Compiled,
};

test "a" {
    var r: PartialInst = undefined;
}
```

### Backtrace

```
#0  0x00007ffff4bca568 in llvm::DataLayout::getAlignmentInfo(llvm::AlignTypeEnum, unsigned int, bool, llvm::Type*) const () from /usr/lib/libLLVM-5.0.so
#1  0x0000000000000000 in ?? ()
```

**Comment by andrewrk** [comment]
Workaround: add a 2nd field to the union.
