### ISSUE TITLE
Segfault when creating dynamically allocated union(enum)

### ISSUE THREAD

**Issue by tiehuis** [zig-lang/zig#723]
```
const Expr = union(enum) {
    Literal: u8,
    Question: &Expr,
};

test "parse" {
    const alloc = @import("std").debug.global_allocator;
    try alloc.create(Expr);
}
```

```
zig test testcase.zig
zsh: segmentation fault (core dumped)
```

### backtrace

```
#0  0x00007ffff34e2e6d in vfprintf () from /usr/lib/libc.so.6
#1  0x00007ffff350c632 in vsnprintf () from /usr/lib/libc.so.6
#2  0x0000555555d7eb1d in buf_appendf (buf=0x555558152d88, format=0x555556ec6490 "[]%s") at /home/me/src/zig/src/buffer.cpp:46
#3  0x0000555555d600ca in get_slice_type (g=0x5555576d8dc0, ptr_type=0x5555578e3590) at /home/me/src/zig/src/analyze.cpp:669
#4  0x0000555555d60177 in get_slice_type (g=0x5555576d8dc0, ptr_type=0x5555578e3590) at /home/me/src/zig/src/analyze.cpp:677
#5  0x0000555555d60177 in get_slice_type (g=0x5555576d8dc0, ptr_type=0x5555578e3590) at /home/me/src/zig/src/analyze.cpp:677
#6  0x0000555555d60177 in get_slice_type (g=0x5555576d8dc0, ptr_type=0x5555578e3590) at /home/me/src/zig/src/analyze.cpp:677
#7  0x0000555555d60177 in get_slice_type (g=0x5555576d8dc0, ptr_type=0x5555578e3590) at /home/me/src/zig/src/analyze.cpp:677
#8  0x0000555555d60177 in get_slice_type (g=0x5555576d8dc0, ptr_type=0x5555578e3590) at /home/me/src/zig/src/analyze.cpp:677
#9  0x0000555555d60177 in get_slice_type (g=0x5555576d8dc0, ptr_type=0x5555578e3590) at /home/me/src/zig/src/analyze.cpp:677
```

**Comment by bnoordhuis** [comment]
It looks to be infinite recursion.  A random backtrace sampling:
```
#16190 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
#16191 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
#16192 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
#16193 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
#16194 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
#16195 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
#16196 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
#16197 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
#16198 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
#16199 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
#16200 0x0000555555d662e7 in get_slice_type (g=0x55555762fdc0, ptr_type=0x55555783a7c0) at /home/bnoordhuis/src/zig/src/analyze.cpp:677
```

**Comment by andrewrk** [comment]
I've narrowed the problem down slightly:

```diff
--- a/src/analyze.cpp
+++ b/src/analyze.cpp
@@ -362,8 +362,10 @@ TypeTableEntry *get_pointer_to_type_extra(CodeGen *g, TypeTableEntry *child_type
     } else {
         assert(bit_offset == 0);
         parent_pointer = &child_type->pointer_parent[(is_const ? 1 : 0)];
-        if (*parent_pointer)
+        if (*parent_pointer) {
+            assert((*parent_pointer)->data.pointer.alignment == byte_alignment);
             return *parent_pointer;
+        }
     }
 
     type_ensure_zero_bits_known(g, child_type);

```

still investigating.
